### PR TITLE
Add poker exercise

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by kytrinyx** [comment]
You're going to run out of exercises to implement in a heartbeat. Did you see the new http://exercism.io/languages/fsharp/contribute page? I can't remember if it's come up in conversation recently or not.

**Comment by ErikSchierboom** [comment]
Actually, I did not! I was about to write such a page myself, but no need for that now :) Looks great.

My aim is to get as much of the exercises as possible ;)

**Comment by kytrinyx** [comment]
> My aim is to get as much of the exercises as possible ;)

That's what I thought :)

**Comment by ErikSchierboom** [comment]
And I'll probably port some of them to C# afterwards. If I can keep myself from trying the just-released Kotlin track...

**Pull request merged**
