### PR TITLE
Convert existing exercises to idiomatic F#. Closes #59

### LINKED ISSUE #59: Use idiomatic F#
Many of the example implementations use classes to implement the desired functionality. However, I'm not sure this is idiomatic F#. Wouldn't just having some functions be more idiomatic? Especially when the class only has one method. In general, should our examples use object-oriented code or functional code? I think we should do the latter.

As an example, consider the `binary` exercise's example implementation:

```fsharp
module Binary

type Binary(input: string) =
    let rec toDecimalLoop acc input = 
        if input = "" then acc
        else 
            let head = input.Chars 0
            let tail = input.Substring 1
            match head with
                | '0' -> toDecimalLoop (acc * 2) tail
                | '1' -> toDecimalLoop (acc * 2 + 1) tail
                | _   -> 0   

    member this.toDecimal() = toDecimalLoop 0 input
```

Testing the functionality is done as follows:
```fsharp
Binary(input).toDecimal()
```

Wouldn't this be a more idiomatic, more functional F# implementation?

```fsharp
module Binary

let toDecimal (input: string) = toDecimalLoop 0 input

let private rec toDecimalLoop acc input = 
        if input = "" then acc
        else 
            let head = input.Chars 0
            let tail = input.Substring 1
            match head with
                | '0' -> toDecimalLoop (acc * 2) tail
                | '1' -> toDecimalLoop (acc * 2 + 1) tail
                | _   -> 0 
```

The test is also a bit more functional:

```fsharp
toDecimal input
```

What do you think?

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR converts the existing exercises to use idiomatic F#. In practice this means that classes are avoided where possible. As an example, this is the old `bob` exercise:

```fsharp
type Bob(statement: string) =
    let isEmpty = String.IsNullOrWhiteSpace input
    let isYell = Seq.exists Char.IsLetter input && input = input.ToUpperInvariant()
    let isQuestion = input.EndsWith "?"

    member this.hey() =
        match input with 
        | _ when isEmpty -> "Fine. Be that way!"
        | _ when isYell -> "Whoa, chill out!"
        | _ when isQuestion -> "Sure."
```

And this is the new exercise:

```fsharp
let hey(input: string) = 
    let isEmpty = String.IsNullOrWhiteSpace input
    let isYell = Seq.exists Char.IsLetter input && input = input.ToUpperInvariant()
    let isQuestion = input.EndsWith "?"

    match input with 
        | _ when isEmpty -> "Fine. Be that way!"
        | _ when isYell -> "Whoa, chill out!"
        | _ when isQuestion -> "Sure."
        | _ -> "Whatever."
```

The same process is applied to the tests, where test classes are converted to plain functions:

```fsharp
[<TestFixture>]
type BinaryTests() =
    
    [<TestCase("1", Result = 1)>]
    [<TestCase("10", Result = 2, Ignore = true)>]
    [<TestCase("11", Result = 3, Ignore = true)>]
    [<TestCase("100", Result = 4, Ignore = true)>]
    [<TestCase("1001", Result = 9, Ignore = true)>]
    [<TestCase("11010", Result = 26, Ignore = true)>]
    [<TestCase("10001101000", Result = 1128, Ignore = true)>]
    member tests.Binary_converts_to_decimal(input) =
        Binary(input).toDecimal()

    [<TestCase("carrot", Ignore = true)>]
    [<TestCase("2", Ignore = true)>]
    [<TestCase("5", Ignore = true)>]
    [<TestCase("9", Ignore = true)>]
    [<TestCase("134678", Ignore = true)>]
    [<TestCase("abc10z", Ignore = true)>]
    member tests.Invalid_binary_is_decimal_0(input) =
        Assert.That(Binary(input).toDecimal(), Is.EqualTo(0))
```

becomes:

```fsharp
[<TestCase("1", ExpectedResult = 1)>]
[<TestCase("10", ExpectedResult = 2, Ignore = "Remove to run test case")>]
[<TestCase("11", ExpectedResult = 3, Ignore = "Remove to run test case")>]
[<TestCase("100", ExpectedResult = 4, Ignore = "Remove to run test case")>]
[<TestCase("1001", ExpectedResult = 9, Ignore = "Remove to run test case")>]
[<TestCase("11010", ExpectedResult = 26, Ignore = "Remove to run test case")>]
[<TestCase("10001101000", ExpectedResult = 1128, Ignore = "Remove to run test case")>]
let ``Binary converts to decimal`` (input: string) =
    toDecimal input

[<TestCase("carrot", Ignore = "Remove to run test case")>]
[<TestCase("2", Ignore = "Remove to run test case")>]
[<TestCase("5", Ignore = "Remove to run test case")>]
[<TestCase("9", Ignore = "Remove to run test case")>]
[<TestCase("134678", Ignore = "Remove to run test case")>]
[<TestCase("abc10z", Ignore = "Remove to run test case")>]
let ``Invalid binary is decimal 0`` (input: string) =
    Assert.That(toDecimal input, Is.EqualTo(0))
```

This example also shows that all tests now use the triple-backticks feature that allows the test function  names to include characters like spaces.

I've also tried to use the default building blocks (lists and tuples) as much as possible, in favor of using types. 

Finally, I've tried to write the tests such that the user is free to implement it however he/she likes.

fyi @kytrinyx

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@jwood803 Would you care to take a look at this?

**Comment by kytrinyx** [comment]
I'm all for this change; deferring to @jwood803 and @ErikSchierboom about merging.

**Comment by jwood803** [comment]
I'm going through this throughout the morning. :}

**Comment by ErikSchierboom** [comment]
Good luck ;)

**Comment by ErikSchierboom** [comment]
@jwood803 Did you manage to find the time to look at this?

**Comment by ErikSchierboom** [comment]
@jwood803 I'll merge this. You can check it out any time you like and then we can fix what is wrong.

**Pull request merged**
