### PR TITLE
Add circle CI support

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR adds support for the CircleCI build server. Unfortunately, I cannot give CircleCI the permissions on the exercism/xfsharp repository, as I am not the owner. This PR should thus not be merged, which is why I marked it as WIP.

@kytrinyx, once you are back from your well-deserved break, would you mind granting the CircleCI repository access to  the xfsharp (xcsharp) repositories? You can find CircleCI here: https://circleci.com

### CODE REVIEW

**Comment by robkeim** [comment]
@ErikSchierboom does this mean that we need to wait until @kytrinyx comes back before checking this in, or can I go ahead and merge this change?

**Comment by ErikSchierboom** [comment]
In theory, this could be merged, but I'd rather leave it open until @kytrinyx's task has been done.

**Comment by robkeim** [comment]
Ok, I'll leave it until she gets back then @ErikSchierboom.

**Comment by kytrinyx** [comment]
I've added Circle CI to this repo.

**Comment by ErikSchierboom** [comment]
Thanks @kytrinyx!

**Pull request merged**
