### PR TITLE
Markdown: Use correct tags for italic and bold text

### PR DESCRIPTION
**Pull request by balazsbotond**
This makes the Markdown exercise conform to the [canonical data][candata]. The issue [has already been discussed][csharppr] in the [xcsharp][xcsharp] repository.

[candata]: https://github.com/exercism/x-common/blob/master/exercises/markdown/canonical-data.json
[csharppr]: https://github.com/exercism/xcsharp/issues/176
[xcsharp]: https://github.com/exercism/xcsharp

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Once again great work @balazsbotond, thanks! 🎉 

We (the current track maintainers) really appreciate all your work on the C# and F# track, with your PR's and your comments on exercism.io, which are both of very high quality. Would you be interested in joining us as a track maintainer of the F# and/or C# track? 

The main task of a track maintainer is to look at issues and PR's, and respond to those. Ideally, you'd also want to help with maintaining the track, by implementing new exercises or fixing existing ones. However, that is not a must by any means, just an extra set of eyes to look at issues logged or PR's sent would be great. The responsibility is shared between all track maintainers of course. 

Are you interested in becoming a maintainer? If not, no problem! We won't hold it against you :)

And thanks again for this PR!

**Comment by robkeim** [comment]
Nice work @balazsbotond!

As @ErikSchierboom mentioned we'd love to have you join us, but even if you're not interested keep up the great work we really appreciate it!

**Comment by balazsbotond** [comment]
This is very kind of you @ErikSchierboom and @robkeim. Of course I'm interested!
I really like exercism and working with you guys have been a pleasure so I gladly accept
the maintainership for both tracks. :)

The only thing I'm not sure I can help you with is implementing new F# exercises. I've started
learning F# in december so I have less than two months of experience with it. I don't feel
my solutions are as polished as those of others, so I don't think it would be fortunate if
I wrote example solutions for new exercises.

But thanks again - I wish every Monday started like this :)

**Comment by robkeim** [comment]
Well then, welcome aboard @balazsbotond :) No need to worry about the F# exercise implementations, for now both the C# and F# tracks have all of the available exercises implemented, and new exercises aren't added on a daily basis so there's not too much work to do on that front.

@ErikSchierboom do you know what we need to do to give him the appropriate permissions?

**Comment by ErikSchierboom** [comment]
@balazsbotond That's fantastic news! Welcome on board! 

@robkeim To actually add @balazsbotond to our tracks, we ask @kytrinyx to add him as a maintainer to the C# and F#. So @kytrinyx, pretty please add @balazsbotond as a maintainer to the C# and F# tracks?

**Comment by kytrinyx** [comment]
Yessss, done! :heart: welcome!

**Comment by ErikSchierboom** [comment]
@kytrinyx Great! Thanks. Welcome aboard @balazsbotond!

**Pull request merged**
