### PR TITLE
Change linked-lists tests and example to use mutation.

### PR DESCRIPTION
**Pull request by theprash**
For #240.

I also fixed an error in `pop` and `shift` where next/prev elements weren't being set to `None` and the list was keeping references to items that had been removed. The tests do not check for this.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
This looks great! Thanks.

I have one small request: could you add a `HINTS.md` file to the exercise's directory? In this file we should link to a page that helps users understand how to use classes in F#. I think [this page](https://fsharpforfunandprofit.com/posts/classes/) would be a great resource to include. You can see an example of how such an `HINTS.md` file looks like [here](https://github.com/exercism/xfsharp/pull/241/files).

**Comment by theprash** [comment]
Why classes? The example implementation still just uses records with mutable fields.

**Comment by theprash** [comment]
I've added hints mentioning both records and classes.

**Comment by ErikSchierboom** [comment]
Oh sorry, I should have of course mentioned records too. I think the hints file is perfect. Merged!

Thanks a lot for all the work! 🎉

**Comment by robkeim** [comment]
Nice job @theprash these changes look good!

**Pull request merged**
