### PR TITLE
Fake testing

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR allows the exercises and their example implementations to be built. Ignored tests will also run. It uses FAKE as the build tool, and it has scripts for both Windows and Unix/Mac.

### CODE REVIEW

**Comment by jwood803** [comment]
Looked at the Travis details...should we update the Travis config to pick up the FAKE script?

**Comment by ErikSchierboom** [comment]
@jwood803 I think so. It should work cross-platform.

**Comment by ErikSchierboom** [comment]
@jwood803 I managed to get the tests working on Travis! See: https://travis-ci.org/exercism/xfsharp/builds/106563792 Stupid case-sensitive paths bugged me for a bit. Shall I merge this PR?

**Comment by jwood803** [comment]
That's awesome! I say ship it! :shipit:

Thanks for finishing what I barely started :}

**Pull request merged**
