### PR TITLE
Remove immutable value from Sum Of Multiples test file

### PR DESCRIPTION
**Pull request by mglodack**

### CODE REVIEW

**Comment by kytrinyx** [comment]
Yeah, this looks simpler. I'll give the track maintainers a chance to review and discuss, but if I don't hear anything for 24 hours, I'll go ahead and merge it.

**Comment by mglodack** [comment]
Awesome :+1: Thanks @kytrinyx

**Comment by ErikSchierboom** [comment]
Looks fine to me :)

**Comment by kytrinyx** [comment]
Thanks y'all!

**Pull request merged**
