### PR TITLE
Acronym: Replace [<TestCase>] tests with individual tests (#298)

### PR DESCRIPTION
**Pull request by balazsbotond**
See #298

### CODE REVIEW

**Comment by robkeim** [comment]
Looks good, thanks @balazsbotond! This can be merged once Travis CI completes.

**Comment by balazsbotond** [comment]
Thanks @robkeim! But I forgot to add the `[<Ignore>]` attributes - please don't merge until I add them.

**Comment by balazsbotond** [comment]
Ok, I've added them - thanks for your patience :)

**Comment by ErikSchierboom** [comment]
Looks great! I think this new version with the individual tests reads so much better. Thanks a lot @balazsbotond!

**Pull request merged**
