### PR TITLE
Fix tests to expect Option values

### PR DESCRIPTION
**Pull request by theprash**

### CODE REVIEW

**Comment by robkeim** [comment]
Strange that this didn't pass the tests... @ErikSchierboom is there a way we can re-run the tests? We don't want to accept pull requests that aren't passing the tests, but the failure doesn't look related to these changes.

**Comment by ErikSchierboom** [comment]
@robkeim Well apparently, AppVeyor changed something in their configuration. The part that breaks this script will be [this line](https://github.com/exercism/xfsharp/blob/master/build.fsx#L44). I've created an [issue](#237) for it.

In general, the Travis build is the more important of the two, as it also checks the validity of the config file. Unfortunately, there is also a [Travis bug](#209), which causes the tests to not run. 

I cannot run the tests again, as @kytrinyx is the owner of the repository and thus the AppVeyor account linked to this repository.

@theprash The PR looks great, but would you mind if I looked at it tomorrow? I should really try to fix the build issues first.

**Comment by ErikSchierboom** [comment]
@theprash I've just merged this [PR](https://github.com/exercism/xfsharp/pull/238) to fix the AppVeyor build. In the process, I've also used the changes you suggested, as otherwise the build failed and I couldn't be certain I fixed the bug. Would you mind rebasing to see if there is anything left to merge? Thanks a lot for finding this by the way.

**Comment by robkeim** [comment]
Thanks @ErikSchierboom for the explanation/fix and echoing Erik's point thanks for the contribution @theprash!

**Comment by theprash** [comment]
No problem. Your changes are fine. Thanks!

**Comment by ErikSchierboom** [comment]
@theprash Thanks you once again!

**Pull request closed without merging**
