### PR TITLE
Added Series exercise

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by jwood803** [comment]
@ErikSchierboom you're doing some work lately! :]

**Comment by ErikSchierboom** [comment]
@jwood803 Expect more!

**Comment by jwood803** [comment]
If you're interested a few F# folks from twitter are in a [Slack chat](https://functionalprogramming.slack.com/home). Feel free to join! Let me know if you need an invite or something.

**Comment by jwood803** [comment]
Oh, and we're using Gitter for Exercism talk. The Roadmap room is where most of the action is.

- [Support](https://gitter.im/exercism/support)
- [Roadmap](https://gitter.im/exercism/roadmap)
- [Organization](https://gitter.im/exercism)

**Comment by ErikSchierboom** [comment]
@jwood803 Thanks for the links. I am interested in the Slack chat, my e-mail address is: erik_schierboom at hotmail.com

**Comment by jwood803** [comment]
@ErikSchierboom I almost forgot about this [link](http://fpchat.com/). See if that gets ya in.

**Pull request merged**
